version: '3.8'
services:
  backend-db:
    image: postgres:14.1-alpine
    container_name: vava-be-db
    restart: on-failure
    environment:
      - POSTGRES_DB=vava
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
